jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            permissions:
              - "Overall/Administer"
            description: "Marvin master"
            assignments:
              - "chocolateen"
          - name: "ape"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Read"
              - "Job/Workspace"
            description: "Pedagogical team member"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Configure"
              - "Job/Move"
              - "Job/Cancel"
              - "Job/Read"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            assignments:
              - "vaugie_g"
          - name: "assist"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"
            description: "Assistant"
            assignments:
              - "nasso"
jobs:
  - file: /var/jenkins_home/job_dsl.groovy